name: OutsideTime
options:
  bundleIdPrefix: com.outsidetime
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: 1

targets:
  OutsideTime:
    type: application
    platform: iOS
    sources:
      - OutsideTime
    resources:
      - path: OutsideTime/Resources
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: OutsideTime/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.outsidetime.app
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    preBuildScripts:
      - name: "Build Core JS Bundle"
        script: |
          cd "${SRCROOT}/.."
          npm run build:core 2>&1 || echo "warning: Core JS build failed — using cached bundle"
          mkdir -p "${SRCROOT}/OutsideTime/Resources"
          cp -f packages/core/dist/core.bundle.js "${SRCROOT}/OutsideTime/Resources/core.bundle.js" 2>/dev/null || true
        basedOnDependencyAnalysis: false
    frameworks:
      - JavaScriptCore.framework
      - Security.framework

  OutsideTimeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - OutsideTimeTests
    dependencies:
      - target: OutsideTime
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.outsidetime.app.tests

schemes:
  OutsideTime:
    build:
      targets:
        OutsideTime: all
        OutsideTimeTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - OutsideTimeTests
